### ISSUE TITLE
auto rest timer does not exactly follow the seconds set

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [ScreteMonge/TestPlugin#6]
First of all, sorry for the barrage of issues im creating! however ive noticed theres some sort of bug with the time in seconds you can input for auto resting in the plugin, it seems to happen before the set time has elapsed, in my example it was at least 10 seconds off

the 2 supplied images are my plugin settings and a stopwatch i started after moving one tile and then stopped as soon as the resting animation played

![image](https://user-images.githubusercontent.com/37377657/192060141-9a9562d8-b1a4-4354-a122-1556e652aa37.png)
![image](https://user-images.githubusercontent.com/37377657/192060157-2520b02f-f478-429b-a930-872b99995ca7.png)

**Comment by Jin-Jiyunsun** [comment]
also without opening yet another issue... short timers will cause your character to rest in cutscenes... its quite funny like they have gotten very bored with the dialoge! but obviously does not look right.. sorry again for opening so many issues!!

**Comment by ScreteMonge** [comment]
Hahaha thank you for reporting these bugs! Don't worry about opening too many issues - that's why they're there, and I honestly don't spend enough time in-game these days to find these bugs myself.

Yeah the seconds one is weird. That's absolutely my failure at basic math and should be easy to fix.

As for the cutscenes: I'll have to do a bit of research to see if there's a good way to fix that. I don't think there's any easy way to determine whether you're in a cutscene or not, but I *might* be able to, say, disable auto-resting while you're in dialogue. We'll see...

**Comment by ScreteMonge** [comment]
My apologies for the delays. The timer should now work accurately. I'll leave this issue open for the time being concerning cutscenes. I haven't really dug into the possibility of stopping Auto-Rest within cutscenes, but as I said before, I don't think there would be an easy way to get around it

**Comment by Zoboomaku** [comment]
I tested this today as it still seemed I was resting long before my auto-rest timer setting. After trying with a setting of 300 seconds (5 minutes), I started resting after 3 minutes. After trying with a setting of 100 seconds, I started resting after 1 minute. It seems the value for this setting represents game ticks/cycles and not seconds as the description states. This is fine, but the description should probably be changed
